sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

script: npm run build-core && node .config/build.js && npm link build/core && npm run build-all

language: node_js
node_js:
  - "6"

cache:
  yarn: true
